version: '3'

volumes:
  standalone_data:

services:
  mysqlcabi:
    container_name: mysqlcabi
    hostname: mysql57
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - standalone_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
  adminer:
    image: adminer
    ports:
      - 8081:8080
